name: manage-azure-policy-5442bfba
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/NIST_SP_800-171_Rev._2_03055927-78bd-4236-86c0-f36125a10dc9/**'
#      - 'initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**'
#      - 'initiatives/IRS1075_September_2016_105e0327-6175-4eb2-9af4-1fba43bdb39d/**'
#      - 'initiatives/Configure_Linux_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_118f04da-0375-44d1-84e3-0fd9e1849403/**'
#      - 'initiatives/Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**'
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
#      - 'initiatives/NIST_SP_800-53_Rev._5_179d1daa-458f-4e47-8086-2a68d0d6c38f/**'
#      - 'initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**'
#      - 'initiatives/_Preview_Australian_Government_ISM_PROTECTED_27272c0b-c225-4cc3-b8b0-f2534b093077/**'
#      - 'initiatives/_Preview_Configure_prerequisites_to_enable_Guest_Attestation_on_Trusted_Launch_enabled_VMs_281d9e47-d14d-4f05-b8eb-18f2c4a034ff/**'
#      - 'initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**'
#      - 'initiatives/_Preview_Configure_Azure_Defender_for_SQL_agents_on_virtual_machines_39a366e6-fdde-4f41-bbf8-3757f46d1611/**'
#      - 'initiatives/_Preview_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**'
#      - 'initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**'
#      - 'initiatives/PCI_v3.2.1_2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**'
#      - 'initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**'
#      - 'initiatives/Canada_Federal_PBMM_4c4a5f27-de81-430b-b4e5-9cbd50595a87/**'
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**'
#      - 'initiatives/Flow_logs_should_be_configured_and_enabled_for_every_network_security_group_62329546-775b-4a3d-a4cb-eb4bb990d2c0/**'
#      - 'initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**'
#      - 'initiatives/ISO_27001_2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**'
#      - 'initiatives/_Preview_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**'
#      - 'initiatives/Configure_Windows_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_9575b8b7-78ab-4281-b53b-d3c1ace2260b/**'
#      - 'initiatives/_Preview_RMIT_Malaysia_97a6d4f1-3bed-4cf4-ac5b-0e444c0408d6/**'
#      - 'initiatives/Configure_Azure_Defender_to_be_enabled_on_SQL_Servers_and_SQL_Managed_Instances_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**'
#      - 'initiatives/_Preview_Configure_machines_to_automatically_install_the_Azure_Monitor_and_Azure_Security_agents_on_virtual_machines_a15f3269-2e10-458c-87a4-d5989e678a73/**'
#      - 'initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**'
#      - 'initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**'
#      - 'initiatives/_Preview_SWIFT_CSP-CSCF_v2021_abf84fac-f817-a70c-14b5-47eec767458a/**'
#      - 'initiatives/CMMC_Level_3_b5629c75-5c77-4422-87b9-2509e680f8de/**'
#      - 'initiatives/_Preview_Windows_machines_should_meet_requirements_for_the_Azure_compute_security_baseline_be7a78aa-3e10-4153-a5fd-8c6506dbc821/**'
#      - 'initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**'
#      - 'initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**'
#      - 'initiatives/New_Zealand_ISM_Restricted_d1a462af-7e6d-4901-98ac-61570b4ed22a/**'
#      - 'initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**'
#      - 'initiatives/_Preview_Deploy_Microsoft_Defender_for_Endpoint_agent_e20d08c5-6d64-656d-6465-ce9e37fd0ebc/**'
#      - 'initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**'
#      - 'initiatives/FedRAMP_Moderate_e95f5a9f-57ad-4d03-bb0b-b1d16db93693/**'
#      - 'initiatives/Audit_Public_Network_Access_Initiative_f1535064-3294-48fa-94e2-6e83095a5c08/**'
#      - .github/workflows/manage-azure-policy-5442bfba.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5442bfba}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/NIST_SP_800-171_Rev._2_03055927-78bd-4236-86c0-f36125a10dc9/**
          initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**
          initiatives/IRS1075_September_2016_105e0327-6175-4eb2-9af4-1fba43bdb39d/**
          initiatives/Configure_Linux_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_118f04da-0375-44d1-84e3-0fd9e1849403/**
          initiatives/Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
          initiatives/NIST_SP_800-53_Rev._5_179d1daa-458f-4e47-8086-2a68d0d6c38f/**
          initiatives/Azure_Security_Benchmark_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**
          initiatives/_Preview_Australian_Government_ISM_PROTECTED_27272c0b-c225-4cc3-b8b0-f2534b093077/**
          initiatives/_Preview_Configure_prerequisites_to_enable_Guest_Attestation_on_Trusted_Launch_enabled_VMs_281d9e47-d14d-4f05-b8eb-18f2c4a034ff/**
          initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**
          initiatives/_Preview_Configure_Azure_Defender_for_SQL_agents_on_virtual_machines_39a366e6-fdde-4f41-bbf8-3757f46d1611/**
          initiatives/_Preview_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**
          initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**
          initiatives/PCI_v3.2.1_2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**
          initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**
          initiatives/Canada_Federal_PBMM_4c4a5f27-de81-430b-b4e5-9cbd50595a87/**
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.3.0_612b5213-9160-4969-8578-1518bd2a000c/**
          initiatives/Flow_logs_should_be_configured_and_enabled_for_every_network_security_group_62329546-775b-4a3d-a4cb-eb4bb990d2c0/**
          initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**
          initiatives/ISO_27001_2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**
          initiatives/_Preview_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**
          initiatives/Configure_Windows_machines_to_run_Azure_Monitor_Agent_and_associate_them_to_a_Data_Collection_Rule_9575b8b7-78ab-4281-b53b-d3c1ace2260b/**
          initiatives/_Preview_RMIT_Malaysia_97a6d4f1-3bed-4cf4-ac5b-0e444c0408d6/**
          initiatives/Configure_Azure_Defender_to_be_enabled_on_SQL_Servers_and_SQL_Managed_Instances_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**
          initiatives/_Preview_Configure_machines_to_automatically_install_the_Azure_Monitor_and_Azure_Security_agents_on_virtual_machines_a15f3269-2e10-458c-87a4-d5989e678a73/**
          initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**
          initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**
          initiatives/_Preview_SWIFT_CSP-CSCF_v2021_abf84fac-f817-a70c-14b5-47eec767458a/**
          initiatives/CMMC_Level_3_b5629c75-5c77-4422-87b9-2509e680f8de/**
          initiatives/_Preview_Windows_machines_should_meet_requirements_for_the_Azure_compute_security_baseline_be7a78aa-3e10-4153-a5fd-8c6506dbc821/**
          initiatives/Enable_Azure_Cosmos_DB_throughput_policy_cb5e1e90-7c33-491c-a15b-24885c915752/**
          initiatives/NIST_SP_800-53_Rev._4_cf25b9c1-bd23-4eb6-bd2c-f4f3ac644a5f/**
          initiatives/New_Zealand_ISM_Restricted_d1a462af-7e6d-4901-98ac-61570b4ed22a/**
          initiatives/FedRAMP_High_d5264498-16f4-418a-b659-fa7ef418175f/**
          initiatives/_Preview_Deploy_Microsoft_Defender_for_Endpoint_agent_e20d08c5-6d64-656d-6465-ce9e37fd0ebc/**
          initiatives/Configure_Advanced_Threat_Protection_to_be_enabled_on_open-source_relational_databases_e77fc0b3-f7e9-4c58-bc13-cb753ed8e46e/**
          initiatives/FedRAMP_Moderate_e95f5a9f-57ad-4d03-bb0b-b1d16db93693/**
          initiatives/Audit_Public_Network_Access_Initiative_f1535064-3294-48fa-94e2-6e83095a5c08/**
